# Generated by Django 5.1.1 on 2024-09-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="item_type",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
