# Generated by Django 5.1.1 on 2024-09-14 03:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_product_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="Item",
        ),
    ]
